### ISSUE TITLE
TypeError when running python -c 'import microstructpy' command 

### ISSUE THREAD

**Issue by Quan711** [kip-hart/MicroStructPy#56]
Howdy,

I have pip installed microstructpy with no error. But when running the python -c 'import microstructpy' command, I got an TypeError like this:

 C:\Users\quanz>python -c "import microstructpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\microstructpy\__init__.py", line 1, in <module>
    import microstructpy.cli
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\microstructpy\cli.py", line 31, in <module>
    from microstructpy.meshing import PolyMesh
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\microstructpy\meshing\__init__.py", line 2, in <module>
    from microstructpy.meshing.trimesh import RasterMesh
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\microstructpy\meshing\trimesh.py", line 19, in <module>
    import pygmsh as pg
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pygmsh\__init__.py", line 1, in <module>
    from . import geo, occ
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pygmsh\geo\__init__.py", line 1, in <module>
    from .geometry import Geometry
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\pygmsh\geo\geometry.py", line 5, in <module>
    import gmsh
  File "C:\Users\quanz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\gmsh.py", line 53, in <module>
    lib = CDLL(libpath)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

Any help would be highly appreciated.

Regards,
Quan

**Comment by kip-hart** [comment]
Hi Quan,

I'm sorry to hear you're having trouble getting started with MicroStructPy. I haven't verified it for myself on Python 3.10. Would it be possible to install running an earlier version, such as 3.7 or 3.8? Let me know if that works for you.

Best,
Kip

**Comment by Quan711** [comment]
Hi Kip,

Thanks for your kind reply. I tried with Jupyter Notebook and it works for me now. I will try to install running an earlier version later this week and let you know if it works.

Best,
Quan

**Comment by kip-hart** [comment]
Hi Quan,

Glad to hear it's working. I'll close the issue, but if there's any related bugs please feel free to re-open.

Best,
Kip
