### ISSUE TITLE
Problem with generating simple PolyMesh from seeds

### ISSUE THREAD

**Issue by jadball** [kip-hart/MicroStructPy#70]
**Describe the bug**
I'm receiving an `AssertionError` when I try to generate a simple PolyMesh from a SeedList:

```
Traceback (most recent call last):
  File "simple_microstructpy.py", line 15, in <module>
    polymesh = microstructpy.meshing.PolyMesh.from_seeds(seed_list, domain, verbose=True)
  File "(...)lib/python3.8/site-packages/microstructpy/meshing/polymesh.py", line 639, in from_seeds
    assert not missing_seeds, str(missing_seeds)
AssertionError: {0, 1, 2, 3, 4}
```

**To Reproduce**
I am using the below script to reproduce this behaviour:

```py
import microstructpy


position_array = [[-0.37342, -0.289708, 0.5128352],
                  [0.204211, 0.41113, 0.4889689],
                  [-0.453932, -0.178443, 0.4169717],
                  [-0.112715, 0.434528, 0.4959116],
                  [-0.12776, -0.0181222, 0.4907776]]
seed_list = microstructpy.seeding.SeedList()
for position in position_array:
    new_seed = microstructpy.seeding.Seed.factory(seed_type="sphere", position=position)
    seed_list.append(new_seed)

domain = microstructpy.geometry.Cube(side_length=1.2)
polymesh = microstructpy.meshing.PolyMesh.from_seeds(seed_list, domain, verbose=True)
```

**Expected behavior**
I'd expect a mesh to be generated here. I suspect the problem is with voro++ under the hood?

**Comment by kip-hart** [comment]
Hi @jadball, sorry for the delayed response - I've been recovering from covid.

I believe the default position for a cube is to put the lower left corner at the origin. If you add "center=[0, 0, 0]" to the keyword arguments for Cube, does that solve the issue?

**Comment by kip-hart** [comment]
Hi @jadball , closing this due to inactivity. Feel free to reopen in the future.

**Comment by kip-hart** [comment]
Hi @jadball no worries thanks for reaching out.

Taking a look at `seed_list[0]`, the seed geometry, phase, and position look good. The one snag is the 'breakdown'. It has the right radius but the center is at the origin, `breakdown=((0.0, 0.0, 0.0, 0.1))`.

Something confusing about the difference between seeds and geometries is that seeds have a 'position' but not geometries. If you try this script again with this change in the for-loop, you should get the pmesh to generate without errors:

`seed_list.append(factory('sphere', position=position, center=position, r=0.1))`

Let me know if that works!
